# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

# CONFIG_ZMK_KEYBOARD_NAME=troy

# Uncomment the following line to enable deep sleep
CONFIG_ZMK_SLEEP=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# # Enable eager debouncing
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y
# Enable Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y

# Enable pairing and bonding
CONFIG_BT_SETTINGS=y
CONFIG_BT_KEYS_OVERWRITE_OLDEST=y
CONFIG_SETTINGS=y
